### ISSUE TITLE
aurelia-ux

### ISSUE THREAD

**Issue by Jenselme** [alflennik/au7#2]
Hi,

I wanted to know if there were reasons for you not to use [aurelia-ux](https://github.com/aurelia/ux)? Do you think there are advantages to use Framework 7 instead of aurelia-ux? I was able to start to play with it today and it looks interesting (integration with Aurelia, easy interaction on CSS with code). I'll need more time to have a good opinion of the framework though.

Anyway, good luck with this project.

**Comment by alflennik** [comment]
Hi Julien,

Aurelia-UX is exciting, and I'm watching it closely. I love a lot of their
ideas and the Aurelia team has accomplished truly amazing things.

That said, I chose Framework7 for its animations! They're really nice :)

That may sound stupid, but that was my actual motivation!

**Comment by Jenselme** [comment]
> That said, I chose Framework7 for its animations! They're really nice :)
> That may sound stupid, but that was my actual motivation!

Not at all. If animations are important to you/your projects.

Thanks for your answer.
