### ISSUE TITLE
Aurelia Blog

### ISSUE THREAD

**Issue by weoreference** [alflennik/au7#7]
Hi Alex,

I really love your Aurelia-F7 framework! It has saved me tons of work.

I have spoken to Rob Eisenberg and Patrick Walters about featuring your article (https://blog.flennik.com/a-challenger-for-ionic-aurelia-framework7-63a53e736b8a) at the main Aurelia Blog (http://blog.aurelia.io/), because I think everyone deserves to know about you and your work. It will be tremendously helpful for beginners like me. Before discovering AU7, I'd spent weeks figuring out how to integrate Aurelia into mobile via Ionic.

May I have your permission to repost your article on our Aurelia blog?
Or -- if you wish -- you may repurpose the article to better expose yourself to the community.

Thanks so much.

Sorry for misusing the Issues feature. (Feel free to delete)

Andy

**Comment by alflennik** [comment]
Oh, thank you Andy! I would appreciate a share of course. I've followed the Aurelia blog and being featured there would be quite exciting. Keep me updated!

**Comment by weoreference** [comment]
Wow, thanks for answering! I'm already submitting your article to Rob Eisenberg personally.

**Comment by EisenbergEffect** [comment]
@alflennik I just wanted to make sure that you were actually ok with us re-posting your article. I'd write a short intro for it and then re-use the content. I'd introduce you as part of the intro. You can send me a bio if you like of course. Is that ok?

**Comment by alflennik** [comment]
Sounds great! Here's a bio.

>The kind of guy who cares about semicolons, tabs and testing (no, no and yes), Alexander Flenniken is a full-stack software engineer in Seattle with seven years and four continents of experience. Find his blog at [blog.flennik.com](http://blog.flennik.com) and tweet him at [@alflennik](https://twitter.com/alflennik).

Oh, and please feel free to email me at a@flennik.com.
